# Generated by Django 4.1.6 on 2023-03-03 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Students',
        ),
    ]
